// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmDcw8rZRVvKo-sBbsGQzRUW-pk3_k0k4',
    appId: '1:851638102781:web:c55acbd3cc82c9e9f0ec94',
    messagingSenderId: '851638102781',
    projectId: 'rubenpos-dfd96',
    authDomain: 'rubenpos-dfd96.firebaseapp.com',
    storageBucket: 'rubenpos-dfd96.firebasestorage.app',
    measurementId: 'G-0KW0W2VBM1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgVTBOYclRrwr3CrnyeByrrBaZsBkJo1U',
    appId: '1:851638102781:android:0e48bad3fd32c961f0ec94',
    messagingSenderId: '851638102781',
    projectId: 'rubenpos-dfd96',
    storageBucket: 'rubenpos-dfd96.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiAHgQTsk8ikDkUccc5cscOQpwiOWNGQE',
    appId: '1:851638102781:ios:16032dad2432d779f0ec94',
    messagingSenderId: '851638102781',
    projectId: 'rubenpos-dfd96',
    storageBucket: 'rubenpos-dfd96.firebasestorage.app',
    iosBundleId: 'com.example.pointOfSale',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiAHgQTsk8ikDkUccc5cscOQpwiOWNGQE',
    appId: '1:851638102781:ios:16032dad2432d779f0ec94',
    messagingSenderId: '851638102781',
    projectId: 'rubenpos-dfd96',
    storageBucket: 'rubenpos-dfd96.firebasestorage.app',
    iosBundleId: 'com.example.pointOfSale',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmDcw8rZRVvKo-sBbsGQzRUW-pk3_k0k4',
    appId: '1:851638102781:web:5b3316336714fc18f0ec94',
    messagingSenderId: '851638102781',
    projectId: 'rubenpos-dfd96',
    authDomain: 'rubenpos-dfd96.firebaseapp.com',
    storageBucket: 'rubenpos-dfd96.firebasestorage.app',
    measurementId: 'G-PV0J9ZC7VT',
  );
}
